---
title: "Mark-recapture analysis"
author: "Matthew Barbour"
date: "`r Sys.Date()`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

# load required libraries
library(tidyverse) 
library(marked)
library(survival)
```

# Wrangle data

```{r}
# load and manage data
df <- read_csv("data/InsectAbundanceSurvival.csv") %>%
  # renaming for brevity
  rename(cage = Cage,
         com = Composition,
         week = Week,
         temp = Temperature,
         rich = Richness) %>%
  mutate(cage = as.character(cage),
         temp = ifelse(temp=="20 C", 0, 3), # put on scale such that coef corresponds to 1 C increase
         temp_com = paste(temp, com)) %>% # create indicator for genetic composition nested within temperature for random effect
  arrange(cage, week)

# create data for survival analysis
survival_df <- df %>%
  # counter information is not relevant for survival (because it is the same), so we summarise across it
  group_by(cage, week, temp, rich, Col, gsm1, AOP2, AOP2.gsoh, com, temp_com) %>%
  summarise_at(vars(BRBR, LYER, Mummy_Ptoids, BRBR_Survival, LYER_Survival, Mummy_Ptoids_Survival), list(mean)) %>%
  ungroup() %>%
  mutate(week_since = week - 2) %>% # week since the full community was added (at week 3)
  filter(week_since > 0) %>%
  mutate(interval_start = week_since - 1,
         interval_stop = week_since) %>%
  # contrasts for allelic effects at each gene
  mutate(aop2_vs_AOP2 = Col + gsm1 - AOP2 - AOP2.gsoh,
         mam1_vs_MAM1 = gsm1 - Col,
         gsoh_vs_GSOH = AOP2.gsoh - AOP2)

mark_recap_wide_df <- survival_df %>%
  # include apparent extinctions. Note that at week 3, parasitoids were still being added, which is 
  mutate(BRBR = ifelse(is.na(BRBR_Survival) == T, 0,
                       ifelse(BRBR_Survival == 1 & BRBR == 0, 0, BRBR_Survival)),
         LYER = ifelse(is.na(LYER_Survival) == T, 0,
                       ifelse(LYER_Survival == 1 & week < 17 & LYER == 0, 0, LYER_Survival)),
         Mummy_Ptoids = ifelse(is.na(Mummy_Ptoids_Survival) == T, 0,
                               ifelse(Mummy_Ptoids_Survival == 1 & week > 3 & week < 17 & Mummy_Ptoids == 0, 0, Mummy_Ptoids_Survival))) %>%
  select(cage, week, temp:temp_com, aop2_vs_AOP2:gsoh_vs_GSOH, BRBR, LYER, Mummy_Ptoids) %>%
  pivot_longer(cols = c(BRBR, LYER, Mummy_Ptoids), names_to = "species", values_to = "survival") %>%
  pivot_wider(names_from = "week", values_from = "survival")

# prepare for marked package
marked_df <- mark_recap_wide_df %>%
  unite(`3`:`17`, col = "ch", sep = "", remove = F) %>% # encounter history
  mutate(species = factor(species),
         temp = factor(temp)) %>%
  select(ch, species, temp, rich, aop2_vs_AOP2) %>%
  as.data.frame()
```

# Cormack-Jolly-Seber capture-recapture model

```{r}
# process data (and set grouping variables)
marked.proc <- process.data(marked_df, 
                            model = "CJS",
                            group = c("species","temp"))

# make design data (from processed data)
marked.ddl <- make.design.data(marked.proc)

# outline formulas for each parameter
Phi.form <- list(formula = ~species + temp + time + rich + aop2_vs_AOP2) # allow survival probability (Phi) to vary by species, temperature treatment, and time, as well as genetic diversity (rich) and AOP2 gene. 
p.form <- list(formula=~species) # allow capture probability (p) to vary among species, which makes sense since some species are harder to detect than others (e.g. LYER prefers to hide underneath basal rosette compared to BRBR).

# make model
cjs.model <- crm(marked.proc, 
                 marked.ddl,
                 model.parameters = list(Phi = Phi.form, 
                                         p = p.form),
                 accumulate = FALSE)
cjs.model

# calculate confidence intervals of parameters
cjs.CIs <- cjs.hessian(cjs.model)

# we're primarily interested in the robustness of the aop2 vs AOP2 effect so we focus on it here
cjs.CIs$results$beta$Phi[c("aop2_vs_AOP2")] # logit scale
exp(cjs.CIs$results$beta$Phi[c("rich","aop2_vs_AOP2")]) # aop2 increases odds of survival by 24% relative to the average allele.
exp(0.4161482) # upper CI (up to 52%)
exp(0.0157780) # lower CI (as low as 1.5%)
```
