---
title: "Plant growth in the absence of insects"
author: "Matthew A. Barbour"
date: "`r Sys.Date()`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

# load required libraries
library(tidyverse)
library(kableExtra)
library(cowplot)
library(lme4)
library(lmerTest)
library(broom.mixed)

# set ggplot theme
theme_set(theme_cowplot())
```

# Wrangle data

```{r}
# load data
ChamberNoInsectsDF <- read_csv("data/PreExperimentNoInsectsPlantBiomass.csv") %>%
  mutate(Cage = as.character(Cage),
         Pot = as.character(Pot))

# conduct analyses at cage level
CageLevelBiomass <- ChamberNoInsectsDF %>%
  # sum biomass across both pots
  group_by(Cage, Temperature, Richness, Composition, Col, gsm1, AOP2, AOP2.gsoh) %>%
  summarise_at(vars(Biomass_g), list(sum)) %>%
  # tidy data
  ungroup() %>%
  select(cage = Cage, temp = Temperature, rich = Richness, com = Composition, Col, gsm1, AOP2, AOP2.gsoh, Biomass_g) %>%
  # adjust temp and rich so effect of +1 C is comparable to +1 genotype
  mutate(temp = ifelse(temp == "20 C", 0, 3),
         rich = rich - 1,
         # define orthogonal constrasts to test for above-average allele effects.
        # aop2_vs_AOP2 must be included first
        aop2_vs_AOP2 = Col + gsm1 - AOP2 - AOP2.gsoh,
        mam1_vs_MAM1 = gsm1 - Col, # aop2_vs_AOP2 must be included in model
        gsoh_vs_GSOH = AOP2.gsoh - AOP2)
```

# Reproduce Table S5

```{r}
# fit model
log_biomass_lmer <- lmer(log(Biomass_g) ~ temp*(rich + aop2_vs_AOP2 + mam1_vs_MAM1 + gsoh_vs_GSOH) + (1|com/temp), 
                        data = CageLevelBiomass)

# reproduce table S5
anova(log_biomass_lmer, type = "1", ddf = "Kenward-Roger") %>%
  kable(., caption = "Analysis of variance for plant biomass (log transformed) in the absence of insects.", booktabs = T) %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```

# Reproduce Fig. S10

```{r}
# calculate 95% confidence intervals, but first remove higher-order statistical interactions
summary(lme4::lmer(log(Biomass_g) ~ temp + rich + aop2_vs_AOP2 + (1|com), data = CageLevelBiomass)) # dropped com:temp, because it was singular, it also doesn't matter for estimating confidence intervals for genetic effect, it would matter if we were trying to estimate temp, which we are only controlling for here.

aop2_CI <- tidy(lmer(log(Biomass_g) ~ -1 + temp + I(AOP2 + AOP2.gsoh) + I(Col + gsm1) + (1|com), 
                     data = CageLevelBiomass), 
                conf.int = T, conf.level = 0.95) %>%
  filter(term %in% c("I(AOP2 + AOP2.gsoh)","I(Col + gsm1)")) %>%
  mutate(allele = c("AOP2","aop2"))
# note that I back transform to original scale for plotting
exp(aop2_CI$estimate[2])

# get the effect of each genotype
mean_geno <- tidy(lmer(log(Biomass_g) ~ -1 + temp + AOP2 + AOP2.gsoh + Col + gsm1 + (1|com), 
                     data = CageLevelBiomass), 
                conf.int = T, conf.level = 0.95) %>%
  filter(term %in% c("AOP2","AOP2.gsoh","Col","gsm1")) %>%
  mutate(allele = c("AOP2","AOP2","aop2","aop2"),
         term = factor(term, levels = c("Col","gsm1","AOP2","AOP2.gsoh"), labels = c("Col","gsm1","AOP2","AOP2/gsoh")))

# plot on original scale
# adding a genotype with an aop2 allele to the population doubles the likelihood of species persistence
plot_AOP2_growth_no_insects <- ggplot(aop2_CI, aes(x = allele, y = exp(estimate))) +
  geom_point(size = 5) +
  geom_point(data = mean_geno, aes(color = term), size = 5, position = position_dodge(width = 0.3)) +
  geom_linerange(aes(ymax = exp(estimate + std.error), ymin = exp(estimate - std.error)), size = 1.5) +
  geom_linerange(aes(ymax = exp(conf.high), ymin = exp(conf.low))) +
  scale_x_discrete(labels = c("AOP2\u2013","AOP2+")) +
  scale_y_continuous("Plant biomass (g)") +
  xlab("Allele") + 
  scale_color_manual(values = c("darkgreen","steelblue","darkorange","firebrick1"), name = "") + 
  theme_cowplot(font_size = 18, line_size = 1)

x11(); plot_AOP2_growth_no_insects

ggsave(plot = plot_AOP2_growth_no_insects, filename = "figures/AOP2-growth-no-insects.pdf", height = 6, width = 8, device=cairo_pdf)
```

